### ISSUE TITLE
Decorators broken.

### ISSUE THREAD

**Issue by baldore** [RogerSep/cthulhu#1]
Looks like they are broken because the new changes in the proposal. See https://github.com/FormidableLabs/radium/issues/430

For now, we can add https://github.com/loganfsmyth/babel-plugin-transform-decorators-legacy so it will work as it did it on Babel 5.

**Comment by davegomez** [comment]
Just learn the new way to do it, use the legacy way will just bring more issues and migration difficulties in the future

**Comment by baldore** [comment]
According to **sebmck** in [this discussion](https://phabricator.babeljs.io/T2645):

> A lot of people are subscribing to this (thank you Phabricator!) so I figure I'll give some more context and an update.
> Decorators were removed in Babel 6 because the decorator proposal has vastly changed from the version that's in Babel 5. I could implement the old proposal in Babel 6 which would make existing Babel 5 decorator code work but when I updated the transformer for the new version of the proposal, your code would break and I'd be violating semver. I'm not willing to do another major bump either as majors in a project like Babel are extremely difficult to coordinate as there's so many integrations using it.

We have to wait until the new proposal is stable. For now, I've integrated the legacy decorators.

**Comment by davegomez** [comment]
> I could implement the old proposal in Babel 6 which would make existing Babel 5 decorator code work but when I updated the transformer for the new version of the proposal, your code would break and I'd be violating semver.

This doesn't make any sense... Decorators are experimental, how the hell I'm going to spect my code never brakes if I'm using highly experimental features?

If there isn't any other way to use them let's install the legacy one, but I hate when people wants to live on the edge but well tied to a fucking mountain =P

**Comment by baldore** [comment]
Decorators were removed. Decorations are being done manually... handcrafting for the win!
